### PR TITLE
Adding missing currency symbols for en-AU and en-NZ

### LINKED ISSUE #45262: Blazor WASM / Browser WASM format as currency shows "AUD" instead of "$"
I have a net5 Blazor app and we are using Globalization to help with currency and date formatting.

Since upgrading to net 5 (from 3.1) numbers formatted with "C" are displaying "AUD" instead of "$" (I am in Australia obviously).
We set the thread culture during the bootstrapping of the app with:

````
CultureInfo.DefaultThreadCurrentCulture   = CultureInfo.CreateSpecificCulture( "en-au" );
CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.CreateSpecificCulture( "en-au" );
````
Here's a screen shot:  https://i.imgur.com/G2uhovG.png

I'm not really sure where to go from here; looks to be a bug with the formatters?
Interestingly this does not affect all locale's equally.
India and Philippines, for example, are displaying the correct symbols.

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/45262.
We were missing currency symbols for AUD and NZD. 
Without this change icudt.dat size: 
1531456.
With the change icudt.dat size:
1525616.
These are non-compressed sizes. I do not fully get why the size decreased. With the fixed bundle, currencies are shown correctly.

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
Looks good but we also need to update the prebuilt .dat files, @directhex can help you there. Maybe that'll also explain the size difference (it isn't deterministic...)

**Comment by mkhamoyan** [comment]
I tried locally for ios  and for me size increased after adding your changes. Interesting that here is mentioned CZK also doesn't work https://github.com/dotnet/runtime/issues/45262#issuecomment-1337664949 but it is in curr-root.txt. Maybe whitelisting this root file doesn't work properly ?

**Comment by ilonatommy** [comment]
> I tried locally for ios and for me also size increased. Interesting that here is mentioned CZK also doesn't work [dotnet/runtime#45262 (comment)](https://github.com/dotnet/runtime/issues/45262#issuecomment-1337664949) but it is in curr-root.txt. Maybe whitelisting this root file doesn't work properly ?

CZK, en-CA and en-IN work, the users just did not use the proper flag:
`<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>`. 
The ICU sizes are indeed unstable so it totally explains the decrease in my case and increase in yours. Thank you for checking it out!

**Review by mkhamoyan — APPROVED** [review]

**Pull request merged**
