### PR TITLE
[wasm] Don't create hybrid .dat for WASM.

### PR DESCRIPTION
**Pull request by ilonatommy**
Connected PRs:
https://github.com/dotnet/sdk/pull/45412
https://github.com/dotnet/runtime/pull/110526
https://github.com/dotnet/runtime/pull/110534
https://github.com/dotnet/runtime/pull/110567

In the process of disabling `HybridGlobalization` feature from WASM, we should remove the icu-transport hybrid package. It fixes the error from the comment:
https://github.com/dotnet/runtime/pull/110567#issuecomment-2532676913

Changes:
- delete the hybrid .json file from filters
- skip building `icudt_hybrid.dat` for WASM but keep it for iOS

### CODE REVIEW

**Review by pavelsavara — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
Actually I think we can remove it from iOS as well. It uses Hybrid Globalization by default now, which in the iOS case means it only uses ICU from the system instead of our own fork.

**Comment by akoeplinger** [comment]
Ah, forgot that I even disabled building this repo for iOS so it's definitely not needed anymore :)

**Comment by ilonatommy** [comment]
> Actually I think we can remove it from iOS as well. It uses Hybrid Globalization by default now, which in the iOS case means it only uses ICU from the system instead of our own fork.

but that feature can be disabled and iOS can run with `HybridGlobalization=false` if users don't agree with its side effects. Why would we stop shipping ICU for them?

**Comment by akoeplinger** [comment]
We've removed that option in .net 9, setting it to false does nothing for iOS anymore.

**Comment by akoeplinger** [comment]
to be clear: the side-effects for iOS aren't as dramatic since it uses the same ICU data that Apple ships with iOS, basically like any other native app would

**Pull request merged**
