### PR TITLE
Rename iOS/tvOS rids to match upcoming changes in dotnet/runtime

### PR DESCRIPTION
**Pull request by directhex**
This changes consolidates on the new iOS/tvOS RIDs, as per https://github.com/dotnet/runtime/pull/49305 and https://github.com/dotnet/runtime/issues/48216

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by directhex** [comment]
I've filed a private build at https://dev.azure.com/dnceng/internal/_build/results?buildId=1029711&view=results to check the packaging

**Comment by directhex** [comment]
This is green, meaning the changes are good

The only question which remains is:

Should we include _fake, redundant RIDs for now_ for compatibility? i.e. reintroduce `ios-x64`, `ios-x86`, `tvos-x64`. This would bloat the package, but would prevent breakage downstream in runtime.git when it picks up the updated ICU package, pending merging of https://github.com/dotnet/runtime/pull/49305

@steveisok, @akoeplinger ?

**Comment by steveisok** [comment]
I'm ok with faking.  I don't think it hurts anything.

**Comment by directhex** [comment]
New internal run: https://dev.azure.com/dnceng/internal/_build/results?buildId=1029869&view=results

**Pull request merged**
