### PR TITLE
Upgrade main to ICU-72 from dotnet/test/icu72-main

### PR DESCRIPTION
**Pull request by steveisok**

### CODE REVIEW

**Comment by steveisok** [comment]
@akoeplinger @directhex can one or both review / approve? I'd like to get this through so it can be more thoroughly tested in runtime.

**Comment by akoeplinger** [comment]
There are a few issues but GitHub fails if I try to comment on them in the PR diff view 😄 

1. You're reverting the changes from https://github.com/dotnet/icu/commit/731657f7ae689b76951d1b103e74aa4f06ab2f49
2. `docs`, `icu4j` and `vendor/double-conversion` folders are added back. also some folders in `tools` that we don't need
3. The CODE_OF_CONDUCT.md and SECURITY.md were deleted
4. The pom.xml in icu/tools/cldr/clrd-to-icu and lib directories wasn't moved to the new location. We modified it to please some security scanner. We should turn those changes into a patch file that we apply.

   Hmm or maybe we don't need the tools/cldr folder at all? Afaik we just kept it because it was in the microsoft/icu fork. We could try deleting it.

**Comment by lewing** [comment]
are we trying to get this in for p4?

**Comment by steveisok** [comment]
> are we trying to get this in for p4?

yes

**Comment by steveisok** [comment]
>    Hmm or maybe we don't need the tools/cldr folder at all? Afaik we just kept it because it was in the microsoft/icu fork. We could try deleting it.

Seems to build fine w/o both tools and lib folders, so I deleted them.

**Comment by akoeplinger** [comment]
Found one more missing and pushed it, looks good now.

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
